language: groovy
jdk:
- openjdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install:
- "./gradlew assemble -x signArchives -POSSRH_USERNAME=${SONATYPE_USERNAME} -POSSRH_PASSWORD=${SONATYPE_PASSWORD}"
before_script:
- "chmod +x gradlew"
script:
- "./gradlew check -POSSRH_USERNAME=${SONATYPE_USERNAME} -POSSRH_PASSWORD=${SONATYPE_PASSWORD}"
- "./gradlew test -POSSRH_USERNAME=${SONATYPE_USERNAME} -POSSRH_PASSWORD=${SONATYPE_PASSWORD}"
notifications:
    webhooks: {{https://im-dichat.xiaojukeji.com/api/hooks/travis/a323f436-bd7e-4908-92a8-f82f7dfa7a33}}
